# Generated by Django 2.2 on 2020-03-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('diagnosis', models.CharField(choices=[('malaria', 'Malaria'), ('typhoid', 'Typhoid'), ('yellow fever', 'Yellow fever'), ('hay fever', 'Hay fever'), ('headache', 'Headache'), ('cough', 'Cough'), ('whooping cough', 'Whooping cough'), ('cold and catarrh', 'Cold and Catarrh'), ('hypertension', 'Hypertension'), ('hyperlipidemia', 'Hyperlipidemia'), ('diabetes', 'Diabetes'), ('back pain', 'Back pain'), ('anxiety', 'Anxiety'), ('obesity', 'Obesity'), ('asthma', 'Asthma'), ('cirrhosis', 'Cirrhosis'), ('arthritis', 'Arthritis'), ('coronavirus', 'Coronavirus'), ('asthma', 'Asthma'), ('hiv', 'HIV'), ('kidney stone', 'Kidney stone'), ('ulcer', 'Ulcer'), ('pneumonia', 'Pneumonia'), ('scabies', 'Scabies'), ('pneumonia', 'Pneumonia'), ('pneumonia', 'Pneumonia'), ('nail fungus', 'Nail fungus'), ('respiratory problems', 'Respiratory problems'), ('obsessive compulsive disorder', 'Obsessive compulsive disorder (OCD)'), ('obesity', 'Obesity'), ('obesity', 'Obesity'), ('pain in joint', 'Pain in joint')], max_length=30)),
                ('vital_signs', models.CharField(blank=True, max_length=255, null=True)),
                ('medications', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
