# Generated by Django 2.2 on 2020-03-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='blood_group',
            field=models.CharField(choices=[('', 'Select Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='diagnosis',
            field=models.CharField(choices=[('', 'Select Diagnosis'), ('anxiety', 'Anxiety'), ('asthma', 'Asthma'), ('arthritis', 'Arthritis'), ('back pain', 'Back pain'), ('cirrhosis', 'Cirrhosis'), ('cough', 'Cough'), ('cold and catarrh', 'Cold and Catarrh'), ('coronavirus', 'Coronavirus'), ('diabetes', 'Diabetes'), ('hay fever', 'Hay fever'), ('headache', 'Headache'), ('hypertension', 'Hypertension'), ('hyperlipidemia', 'Hyperlipidemia'), ('hiv', 'HIV'), ('kidney stone', 'Kidney stone'), ('malaria', 'Malaria'), ('nail fungus', 'Nail fungus'), ('obsessive compulsive disorder', 'Obsessive compulsive disorder (OCD)'), ('obesity', 'Obesity'), ('pain in joint', 'Pain in joint'), ('pneumonia', 'Pneumonia'), ('respiratory problems', 'Respiratory problems'), ('scabies', 'Scabies'), ('typhoid', 'Typhoid'), ('ulcer', 'Ulcer'), ('whooping cough', 'Whooping cough'), ('yellow fever', 'Yellow fever')], max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='medications',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='vital_signs',
            field=models.CharField(max_length=255),
        ),
    ]
